version: '3.4'

services:
  deepfakedetection:
    image: deepfakedetection
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - bot_token=1168941932:AAGiYEV79cjssoQX_rZ5IwE4nbFhliKlh5M
      - bot_user_name=imagedetect_bot
      - URL=https://cf45064e05ed.ngrok.io